### ISSUE TITLE
AbstractMethodError when calling SonarInventory#getStackInSlot

### ISSUE THREAD

**Issue by josephcsible** [SonarSonic/Sonar-Core#55] opened 2018-02-04 23:25 UTC
Originally reported as McJty/XNet#228. When [we call `getStackInSlot`](https://github.com/McJty/XNet/blob/a3821cb2ca7619e0ddb0be43877af7c27d164ddc/src/main/java/mcjty/xnet/apiimpl/items/ItemChannelSettings.java#L471), an AbstractMethodError results. At that location, `handler` is an instance of SonarInventory ([it came from a `TileEntityCalculator.Atomic`](https://github.com/SonarSonic/Calculator/blob/a52e99c3894d65f7e1199ecd93c0dd0ece9acfa9/src/main/java/sonar/calculator/mod/common/tileentity/misc/TileEntityCalculator.java#L121) if that's relevant). It looks like AbstractSonarInventory, [which SonarInventory inherits from](https://github.com/SonarSonic/Sonar-Core/blob/ec63c6d3f86d7916ead07c7282b7b41b362e798e/src/main/java/sonar/core/inventory/AbstractSonarInventory.java#L22), [does indeed implement this method](https://github.com/SonarSonic/Sonar-Core/blob/ec63c6d3f86d7916ead07c7282b7b41b362e798e/src/main/java/sonar/core/inventory/AbstractSonarInventory.java#L77), so I'm not sure what's causing this.

**Comment by abdullamu** [comment] 2018-02-05 14:28
downgrading to earlier version works without crash, but i had to downgrade calculator and flux network otherwise it crash.

**Comment by Fatmice** [comment] 2018-02-18 22:52
I'm getting a similar crash.  World will crash on load.  Here is the multiMC instance containing the two worlds, pre has setup for crash, and post where world is corrupt.
https://www.dropbox.com/s/n1ogcyvoa4dkrcn/Calculator%20Crash%20Repro.zip?dl=0

Crash log
https://cdn.discordapp.com/attachments/323830072996003840/414913647488401409/crash-2018-02-18_14.35.27-server.txt

**Comment by SonarSonic** [comment] 2018-06-01 10:31
Forgot to close this a while back, was caused by a `IItemHandler` and `IInventory` being implemented on the same class, meaning their subtly different `getStackInSlot` methods clashed.

**Closed as completed by SonarSonic** 2018-06-01 10:31 UTC
